# Generated by Django 3.0.6 on 2020-05-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('Food_Group', models.CharField(blank=True, max_length=255, null=True)),
                ('Calories', models.PositiveIntegerField(blank=True, null=True)),
                ('Fat', models.FloatField(blank=True, null=True)),
                ('Protein', models.FloatField(blank=True, null=True)),
                ('Carbohydrate', models.FloatField(blank=True, null=True)),
                ('Sugars', models.FloatField(blank=True, null=True)),
                ('Fiber', models.FloatField(blank=True, null=True)),
                ('Cholesterol', models.FloatField(blank=True, null=True)),
                ('Saturated_Fats', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
