# Generated by Django 3.0.6 on 2020-05-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Calories',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Carbohydrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Cholesterol',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Fat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Fiber',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Food_Group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='PID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Protein',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Saturated_Fats',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Sugars',
            field=models.FloatField(null=True),
        ),
    ]
