# Generated by Django 3.0.6 on 2020-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200519_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Carbohydrate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Cholesterol',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Fat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Fiber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Protein',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Saturated_Fats',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Sugars',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
