# Generated by Django 3.0.6 on 2020-06-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_availablitylevel_availablityzone_category_foodgroup_foodnutrition_problem_processing_vitamins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodnutrition',
            old_name='Vitamins',
            new_name='Vitamin',
        ),
    ]
