# Generated by Django 3.0.6 on 2020-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Transgender')], max_length=1),
        ),
    ]
