# Generated by Django 3.0.2 on 2020-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200513_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DailyCalories',
            field=models.PositiveIntegerField(default=299),
            preserve_default=False,
        ),
    ]
