# Generated by Django 3.0.6 on 2020-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_profile_bmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Goals',
            field=models.CharField(choices=[('1', 'Extreme Loose Weight'), ('2', 'Minor Loose Weight'), ('3', 'Maintain Weight'), ('4', 'Weight gain'), ('5', 'Extreme Weight gain')], max_length=1),
        ),
    ]
