# Generated by Django 3.0.6 on 2020-06-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20200519_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Activity',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='BMI',
            new_name='bmi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='BMR',
            new_name='bmr',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='DailyCalories',
            new_name='dailyCalories',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Goals',
            new_name='goals',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Weight',
            new_name='weight',
        ),
    ]
