# Generated by Django 3.0.6 on 2020-06-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200604_2026'),
        ('info', '0007_auto_20200605_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodNutrition')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Profile')),
            ],
        ),
    ]
