# Generated by Django 3.0.6 on 2020-06-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200604_2026'),
        ('info', '0008_daily_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('BloodGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.BloodGroup')),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Problem')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Profile')),
            ],
        ),
    ]
