# Generated by Django 3.0.6 on 2020-06-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_bloodgroup_medicalform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalform',
            name='Profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.Profile'),
        ),
    ]
