# Generated by Django 3.0.6 on 2020-06-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20200607_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='FoodChoice',
            new_name='foodChoice',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='LactoseIntolerance',
            new_name='lactoseIntolerance',
        ),
    ]
