# Generated by Django 3.0.6 on 2020-06-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200604_2026'),
        ('info', '0012_auto_20200607_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_Intake',
            new_name='DailyIntake',
        ),
    ]
