# Generated by Django 3.0.6 on 2020-06-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20200607_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyIntake',
        ),
    ]
