# Generated by Django 3.0.6 on 2020-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_dailyintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyintake',
            name='Mark',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
