# Generated by Django 3.0.6 on 2020-06-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_dailyintake_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyIntake',
        ),
    ]
