# Generated by Django 3.0.6 on 2020-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_delete_dailyintake'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
