# Generated by Django 3.0.6 on 2020-06-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200604_2026'),
        ('info', '0019_dailydiet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydiet',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.FoodNutrition'),
            preserve_default=False,
        ),
    ]
