# Generated by Django 3.0.6 on 2020-06-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20200608_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydiet',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='dailydiet',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='dailydiet',
            old_name='Mark',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='dailydiet',
            old_name='Profile',
            new_name='profile',
        ),
    ]
