# Generated by Django 3.0.6 on 2020-06-08 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_auto_20200608_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydiet',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 8, 19, 11, 39, 423280, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='batman', max_length=255),
            preserve_default=False,
        ),
    ]
